server:
  port: 8080
  
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
    initialization-mode: always

student:
  create:
    code: "ERR001"
    message: "El estudiante con ID %s ya existe"
  empty:
    code: "ERR002"
    message: "No se encontro resultados"
